title: "José L. Cómbita"
author: "José L. Cómbita"
description: "Independent Researcher"
permalink: /:title/
lang: "en" # English language
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_social: true          #
show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV", url: "JoseLuisCombita_CV.pdf", target = "_blank"}
  - {title: "About", file: "about.md"}
  - {title: "R for Ecology", url: "https://www.youtube.com/@ecodr9010"}
  - {title: "Blog", file: "blog.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: "Mail", icon: envelope, url: "mailto:jlcom7@gmail.com"}
  - {title: "Github", icon: github, url: "https://github.com/jlcom"}
  - {title: "X", icon: X, url: "https://x.com/jlcomb"}
  
  

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
